### ISSUE TITLE
执行python main.py时产生的一个报错，但无法定位位置

### ISSUE THREAD

**Issue by YMCVICTOR** [pengzhendong/streaming-sensevoice#16]
![Snipaste_2024-10-24_16-57-15](https://github.com/user-attachments/assets/7ae00f42-8a73-441d-93d3-3daeebabbe4f)
能正常执行结果，但是会有一个报错，请问这个是哪里出现的问题呢？

**Comment by ISJDOG** [comment]
这个是 `funasr` 的内部错误，具体代码在 [`funasr/utils/dynamic_import.py#L40`](https://github.com/modelscope/FunASR/blob/2a296ab51167ed7bd8c6025e7c2974f831812d8b/funasr/utils/dynamic_import.py#L40) ，正常来说是不会影响加载的，你可以删除 [`streaming_sensevoice/sensevoice.py#L677`](https://github.com/pengzhendong/streaming-sensevoice/blob/e0ddefbe0ea070c66b6e4cf9a9436b61fb14af59/streaming_sensevoice/sensevoice.py#L677) 以移除这个错误。
