### ISSUE TITLE
[Question] 如何设定其他语言？

### ISSUE THREAD

**Issue by YunzhaoLu** [pengzhendong/streaming-sensevoice#21]
如果使用粤语或EN模型，怎么设定Language?

**Comment by pengzhendong** [comment]
https://github.com/pengzhendong/streaming-sensevoice/blob/1927386837a3b243502de354e67ff055dcd33b7a/streaming_sensevoice/streaming_sensevoice.py#L130

add param: `language="yue"`

**Comment by pengzhendong** [comment]
fixed: https://github.com/pengzhendong/streaming-sensevoice/commit/d0d11183dc41f1aa15848dd0f9816ebed10c4196
