### ISSUE TITLE
实时推理中的标点恢复

### ISSUE THREAD

**Issue by EvenYan** [pengzhendong/streaming-sensevoice#26]
在使用流式实时推理时，找了一圈源码，没有看到标点恢复的参数设置。请问如果想在实时场景中恢复标点符号，应该如何去做？

**Comment by SNTube** [comment]
`streaming_sensevoice`中的`textnorm`是标点恢复

**Comment by EvenYan** [comment]
> `streaming_sensevoice`中的`textnorm`是标点恢复

thanks

**Comment by weisliey** [comment]
![image](https://github.com/user-attachments/assets/9626f4ec-230b-49ff-baa8-e3cdefc7c3fb)
大佬，设置 了textnorm=True，返回结果还是没有标点符号，是什么原因啊？
