### ISSUE TITLE
识别结果中许多词语连起来了 如何解决

### ISSUE THREAD

**Issue by feixukeji** [pengzhendong/streaming-sensevoice#27]
识别结果中许多词语连起来了，如“kilogramis the last basespacesi unitit to be definededte a physical objectjectsince seventyventeen9one kilogram has been definedfined as exactactly the the messssof”，请问如何解决？

**Comment by pengzhendong** [comment]
由于 sensevoice 时间戳效果比较差，确实可能导致这个问题。除了调大 chunk size，或者改成句子级别的流式，此项目暂时无好的解决方法。
