### ISSUE TITLE
如何获取情感和事件的识别结果？

### ISSUE THREAD

**Issue by WANGRUI-ZB** [pengzhendong/streaming-sensevoice#29]

**Comment by qiuqiu-879** [comment]
同问

**Comment by pengzhendong** [comment]
https://github.com/pengzhendong/streaming-sensevoice/issues/6

**Comment by justplus** [comment]
如果要输出怎么做？

**Comment by justplus** [comment]
如果要想输出情绪、语种等标签，需要将padding设置为0，同时inference的最后self.model.ctc.log_softmax(encoder_out)[0, 0:]。输出的结果为：
<|zh|><|NEUTRAL|><|Speech|><|woitn|>钉<|zh|><|NEUTRAL|><|Speech|><|woitn|>今天又不<|zh|><|EMO_UNKNOWN|><|Speech|><|woitn|>嗯。
将这个结果做下后处理即可。
