### ISSUE TITLE
时延问题

### ISSUE THREAD

**Issue by WangFeiji0928** [pengzhendong/streaming-sensevoice#32]
没100ms的chunk处理时延大致180ms左右，非流式ASR直接输出整句结果大致时延80ms。请问为什么会这样？还是我时延算的不对。
def main():
    contexts = ["停止"]
    model = StreamingSenseVoice(contexts=contexts)

    samples, sr = sf.read("data/output_spk1.wav")
    samples = (samples * 32768).tolist()

    step = int(0.1 * sr)
    for i in range(0, len(samples), step):
        start_time = time.time()
        is_last = i + step >= len(samples)
        for res in model.streaming_inference(samples[i : i + step], is_last):
            process_time = (time.time() - start_time) * 1000  # 转换为毫秒
            print(f"处理延迟: {process_time}ms")
            print(f"音频时间戳: {res['timestamps']}")
            print(f"文本：{res['text']}")

**Comment by pengzhendong** [comment]
非流式的代码呢？

**Comment by WangFeiji0928** [comment]
> 非流式的代码呢？

非流式用的就是sensevoice官方给的那个

**Comment by pengzhendong** [comment]
官方的是不是默认用了显卡，这里默认没用

**Comment by WangFeiji0928** [comment]
> 官方的是不是默认用了显卡，这里默认没用

果然是这样，感谢佬
