### ISSUE TITLE
BUG: command [python main.py] not work

### ISSUE THREAD

**Issue by shaunhurryup** [pengzhendong/streaming-sensevoice#33]
I replaced the default WAV file with my own which has 15 minutes, but it failed to work.

```py
    # samples, sr = sf.read("data/test_16k.wav")
    samples, sr = sf.read("data/investment.wav")
```

$ python main.py

Downloading Model to directory: /Users/xxx/.cache/modelscope/hub/iic/SenseVoiceSmall
2024-12-23 15:53:07,896 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
Loading remote code failed: model, No module named 'model'
Traceback (most recent call last):
  File "/Users/xxx/xxx/streaming-sensevoice/main.py", line 37, in <module>
    main()
  File "/Users/xxx/xxx/streaming-sensevoice/main.py", line 31, in main
    for res in model.streaming_inference(samples[i : i + step], is_last):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/streaming-sensevoice/streaming_sensevoice/streaming_sensevoice.py", line 128, in streaming_inference
    self.fbank.accept_waveform(audio, is_last)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/online_fbank/online_fbank.py", line 34, in accept_waveform
    super().accept_waveform(self.sample_rate, samples)
TypeError: accept_waveform(): incompatible function arguments. The following argument types are supported:
    1. (self: _kaldi_native_fbank.OnlineFbank, sampling_rate: float, waveform: List[float]) -> None

Invoked with: <online_fbank.online_fbank.OnlineFbank object at 0x30f1f7d10>, 16000, [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0

**Comment by WanwanLinLin** [comment]
你这个音频文件是立体声，把它改成单声道就可以了
