### ISSUE TITLE
请问这种实现方式对情绪和事件识别有什么影响？

### ISSUE THREAD

**Issue by WangFeiji0928** [pengzhendong/streaming-sensevoice#6]
多任务共享encoder的情况下，应该是每次输出一个chunk的识别结果都会输出情绪和事件。请问有没有好的处理方式以及有没有测试过识别结果

**Comment by pengzhendong** [comment]
目前的处理方式是忽略情绪和声音时间，chunk 太小，情绪和事件的识别应该不准，你可以尝试句子级别的流式
