### ISSUE TITLE
[Feature] 是否有计划支持 Batch 推理？

### ISSUE THREAD

**Issue by ISJDOG** [pengzhendong/streaming-sensevoice#7]
我正在将流式推理功能包装成 `websocket` 和 `webrtc` API ，但是目前 `StreamingSenseVoice` 并没有考虑复用显存中的模型，目前我的解决方法是改造 `streaming_inference` ，将 `cur_idx` `decoder` `fbank` `caches` 存入单独的对象，让每个业务线程自行维护，并在推理时传入。

这个方法似乎并不优雅，请问在 Batch 推理方面有相应的开发计划吗？

**Comment by pengzhendong** [comment]
see https://github.com/pengzhendong/streaming-sensevoice/commit/041aaaf1ff0b054d782d0d20faf550fea75dc8d0
